### PR TITLE
De-duplicate CMake logic for samples

### PR DESCRIPTION
**Pull request by kpet**
Signed-off-by: Kevin Petit <kevin.petit@arm.com>

### CODE REVIEW

**Comment by MathiasMagnus** [comment]
The current control of install layout seems more code than I believe it could be (my guts are telling me). It is tangential to the deduplication at hand, so I'll defer "fixing" that once I come with a better way. (Multi-config generators should be taking care of this automatically, or generator expressions to install() should do the trick. No need for if()s and foreach()s. (At least that's the theory)

**Review by MathiasMagnus — APPROVED** [review]

**Comment by kpet** [comment]
Thanks for the review! Yes, agree this can probably be made simpler. I was just looking to reduce the duplication first.

**Review by bashbaug — APPROVED** [review]
This is a nice improvement and can be merged anytime.

FWIW, I went through a similar de-duplication recently in some of my personal samples.  A few enhancements I've found useful that we may want to make shortly are:

1. Move the OpenCL version setting into the CMake function as well to reduce boilerplate.
2. Add the ability to install additional files, such as files containing OpenCL kernels.
3. Add the ability to link with additional libraries, say for OpenGL visualization or utility functions.

In case it's helpful, see:

* [CMake Function](https://github.com/bashbaug/SimpleOpenCLSamples/blob/master/samples/CMakeLists.txt#L29)
* [Example Usage](https://github.com/bashbaug/SimpleOpenCLSamples/blob/master/samples/00_enumopencl/CMakeLists.txt#L21)

**Comment by kpet** [comment]
+1 on @bashbaug's suggestions. That's the way to go!

**Comment by kpet** [comment]
I've created https://github.com/KhronosGroup/OpenCL-SDK/issues/22 to cover enhancing the function further as per Ben's suggestions. Merging this PR as is.

**Pull request merged**
