### PR TITLE
Add python examples

### PR DESCRIPTION
**Pull request by inducer**

### CODE REVIEW

**Comment by inducer** [comment]
Here's the thing: While I hold the copyright for *some* of these files, these:
- `python/black-hole-accretion.py`
- `python/n-body.py`
- `python/pi-monte-carlo.py`
are not mine to assign copyright for. @numa65536 might know more. I've already reformatted these files to pass flake8 (so that's probably worth preserving), but maybe they should be added as part of a separate PR for which @numa65536 can sign the CLA.

**Comment by inducer** [comment]
Nvm about the CLA: I've removed these files and preserved my changes to them in https://github.com/inducer/pyopencl/pull/470.

I've also force-pushed to ensure they're not part of the history.

**Review by bashbaug — APPROVED** [review]
This looks good to me and I think we can merge this any time.  I was able to run all of these samples on our implementation and they behave as expected.

The most interesting part I think is the CI.  It didn't seem to run on the PR for some reason.  I'm a little curious to know how long it takes to run, but given that this repo is fairly low traffic it's unlikely to be a concern for a while.

At some point I think we'll want a writeup or link that describes what these samples are doing, but that can come in a separate PR.

Thank you for your contribution (and your work on PyOpenCL)!

**Comment by bashbaug** [comment]
One other documentation-related comment: it would be nice to have a README with a link to PyOpenCL and installation instructions, and/or a "requirements.txt".

**Comment by inducer** [comment]
(Fixed another CI scripting mistake in 6c6cade, sorry!)

**Review by alycm — APPROVED** [review]
LGTM.

**Comment by alycm** [comment]
> The most interesting part I think is the CI. It didn't seem to run on the PR for some reason.

It was showing me the below message

> First-time contributors need a maintainer to approve running workflows. [Learn more.](https://docs.github.com/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) 

So I clicked "approve".   The difference appears to be that I have maintainer privileges, which I have now used to grant you (@bashbaug) the same.

**Comment by alycm** [comment]
Thanks for fixing that linter CI issue so quickly @inducer !

Ignoring all the noise that had on the first run it did hit on the files in the PR as well:

```
./python/demo.py:18:80: E501 line too long (80 > 79 characters)
./python/transpose.py:69:80: E501 line too long (81 > 79 characters)
./python/transpose.py:91:80: E501 line too long (82 > 79 characters)
./python/transpose.py:182:80: E501 line too long (83 > 79 characters)
./python/transpose.py:223:25: E127 continuation line over-indented for visual indent
./python/dump-properties.py:20:80: E501 line too long (81 > 79 characters)
./python/dump-properties.py:24:25: E128 continuation line under-indented for visual indent
./python/dump-properties.py:50:21: E265 block comment should start with '# '
./python/dump-properties.py:51:21: E265 block comment should start with '# '
./python/dump-properties.py:58:80: E501 line too long (80 > 79 characters)
./python/dump-properties.py:64:37: E128 continuation line under-indented for visual indent
./python/dump-properties.py:75:80: E501 line too long (83 > 79 characters)
./python/dump-properties.py:76:41: E128 continuation line under-indented for visual indent
```

but now it doesn't, the CI change looks correct, but is output being suppressed somehow?

**Comment by inducer** [comment]
Sorry about the repeated CI failures, and thanks for your patience! This is good to go from my end.

**Comment by alycm** [comment]
Ignore the previous comment, I completed missed the `setup.cfg`.

All LGTM.

**Comment by inducer** [comment]
> Ignore the previous comment, I completed missed the `setup.cfg`.

Yup, exactly. You can judge me if you like :), but it's (morally) the [same one I use in pyopencl](https://github.com/inducer/pyopencl/blob/3391f749995a03af25647bfdfb985da7da4d1364/setup.cfg).

**Comment by bashbaug** [comment]
Merging as discussed in the OpenCL working group.

**Pull request merged**
